### ISSUE TITLE
2 Issues with All Subs Plus 1.0.1

### ISSUE THREAD

**Issue by TwilightMercy** [burekasKodi/repository.burekasKodi#1]
אהלן,

2 בעיות שמצאתי בגרסת All Subs Plus 1.0.1 (מחפש דרך לינקים המגיעים מReal Debrid):

1. חיפוש סרטים לא נותן תוצאות מאתר Ktuvit. (בסדרות כן)
2. התרגום מכונה אוטומטי לא עובד, נותן שגיאה

**Comment by burekasKodi** [comment]
בנושא הכתוביות נא לכתוב את השאלות כאן:
https://htmag.co.il/phpbb/viewtopic.php?f=12&t=373769

**Comment by TwilightMercy** [comment]
אין בעיה. ולצרף לוג במצב debug?

**Comment by TwilightMercy** [comment]
בבקשה

https://htmag.co.il/phpbb/viewtopic.php?f=12&t=373769&p=3269449#p3269449+

**Comment by TwilightMercy** [comment]
יצא לך להסתכל?
